openapi: 3.1.0
info:
  version: 1.0.0
  title: Products app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is documentation of contacts app
tags:
  - name: Products
    description: Operations with products.
servers:
  - url: http://localhost:3000
  - url: https://products-app-v8pb.onrender.com
paths:
  /products:
    get:
      $ref: ../swagger/paths/products/get.yaml
    post:
      $ref: ../swagger/paths/products/post.yaml
  /products/{productId}:
    get:
      $ref: ../swagger/paths/products/{id}/get.yaml
    delete:
      $ref: ../swagger/paths/products/{id}/delete.yaml
    patch:
      $ref: ../swagger/paths/products/{id}/patch.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
